# Site settings
title: n8g with jekyll
email: nate@nategeslin.com
description: "Jekyll sandbox.  Lets play with Jekyll!"
baseurl: ""
#baseurl: "http://localhost:4000"
url: "http://localhost:9000"
exclude: ["sass", "node_modules", "boilerplate.html", "Gruntfile.js", "README.md", "LICENSE", "package.json"]
#twitter_username
#github_username
#gplus_username
#tumblr_username
#flickr_username
#500px_username

# Build settings
markdown: rdiscount
permalink: pretty
highlighter: pygments 