# Site settings
title: n8g.com
email: nate@nategeslin.com
description: "Anything and everything {but mostly computer stuff}"
baseurl: ""
#baseurl: "http://localhost:4000"
#url: ""
url: "http://localhost:9000"
exclude: ["sass", "bower_components", "docs", "doc_assets", "node_modules", "boilerplate.html", "CHANGELOG.md", "Gruntfile.js", "README.md", "LICENSE", "package.json", "bower.json", "post-receive"]
#twitter_username
#github_username
#gplus_username
#tumblr_username
#flickr_username
#500px_username

# Build settings
markdown: rdiscount
permalink: pretty
highlighter: pygments 